### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by mrlinuxdude** [Tail-R/eww_dotfiles#3]
Hi Thanks for dots. they are amazing looks wonderful  can't wait use them

Sorry i'm new to eww trying understand it. I just want to know how to install.  i have read a lot of stuff on net. I get you install eww first right? I just want to know something i'm planning on installing hypr.  i think it comes with waybar by default if you know. If so how do change it to use eww. Just part i'm stuck on.

**Comment by Tail-R** [comment]
Sorry for my bad english

First, install rust and cargo as instructed in the official documentation. 

Next, follow the documentation to clone the eww source and build it. (There is no problem if you can use pacman's one.)

I've only used hyprland a little, but you probably have a command to start waybar near the top of a file named something like hyprland.conf. Comment it out and replace it with the command that starts eww.

in my case
eww/bar/launch.sh and eww/popup/launch.sh is
the launchscripts 

-----Notes-----
Don't forget to chmod execute permissions for all scripts!

My scripts use commands such as acpi and wmctrl, but they may not be included by default depending on your environment.

**Comment by Tail-R** [comment]
Actually using eww is a headache lol

**Comment by mrlinuxdude** [comment]
Well it takes time learn i bet. don't get headache :) its really amazing for your work. Thanks.  I will be back let you know how everything went. It will take me couple of weeks i will post back with my desktop.
